### ISSUE TITLE
NEAR balance doesn't change after staking on web wallet

### ISSUE THREAD

**Issue by ClanonymousX** [Narwallets/meta-pool#10]
On NEAR web wallet, NEAR balance doesn't change after staking and stNEAR is always 0. 

On metapool staking page, the balances are correct.
![narwallet](https://user-images.githubusercontent.com/87243253/125176245-e348d300-e186-11eb-9ec5-c59356521e5e.png)
![near_wallet](https://user-images.githubusercontent.com/87243253/125176246-e3e16980-e186-11eb-9c96-68affaeba4c2.png)

**Comment by luciotato** [comment]
please check in the "Account Detail" section of the NEAR Web wallet. The meta-pool acts as a staking-pool (you can stake into it with the same interface as a staking-pool) and also as a NEP-141 Token (it provides stNEAR to you)

Did some testing and it looks like it's working (after refreshing the NEAR WEB wallet)

Regarding the NEAR balance: The real balance in that account is 311(N), but Looks like NEAR WEB Wallet it's considering what's in the meta-pool as "in staking-pools" (it's correct) so it sums that as part of the "NEAR balance"

![image](https://user-images.githubusercontent.com/1760905/125362755-d0c8c800-e345-11eb-986e-571f07e1a8b8.png)

![image](https://user-images.githubusercontent.com/1760905/125362788-dc1bf380-e345-11eb-8eeb-98a346741080.png)
