### ISSUE TITLE
Two feedback about user experience 

### ISSUE THREAD

**Issue by wikitoptop** [Narwallets/meta-pool#12]
Two feedback about user experience ① after adding mobility, it will automatically jump to the main page, which will not be the case for other operations. If I want to add mobility again, I need to click this page again. ② I click the wallet without any response. I can't copy the wallet address or disconnect the link of the wallet. It's very inconvenient.

**Comment by wikitoptop** [comment]
[https://twitter.com/wikitoptop/status/1426760898660630531?s=19](url)

**Comment by fercargo** [comment]
closed, link not availabe
