### ISSUE TITLE
My observation and suggestion

### ISSUE THREAD

**Issue by thb030100** [Narwallets/meta-pool#5]
1. You guys can change the word below, just "Not enough balance". It will make UX much better [https://prnt.sc/10rntu2](https://prnt.sc/10rntu2)
2. You should add some features to let users know how much fee they will gonna cost. Just a simple method but very useful to make a better experience for users [https://prnt.sc/10rnxku](https://prnt.sc/10rnxku) 
3. Available [https://prnt.sc/10rnxku](https://prnt.sc/10rnzr4)
4. I expect to see the stNEAR to be shown on near wallet, it might need in some situation [https://prnt.sc/10roqld](https://prnt.sc/10roqld)
5. It should have some kind of feature or number that let users know how much $META token is minted, for example using APY like others blockchain. It just a suggestion. [https://prnt.sc/10rot9s](https://prnt.sc/10rot9s)

**Comment by luciotato** [comment]
I'll move number 4 to narwallets-chrome-extension
It's in the roadmap to show NEP-141 tokens

5. good point. It's not clear how to show actual $META awards. All of those are internal transactions. I guess we should add in the FAQ explicit details on how the $META is awarded.

**Comment by fercargo** [comment]
fixed on 2021
